# Site settings
title: Orthonomie Plus - Mobilité et Confort
email: info@orthonomieplus.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://orthonomieplus.com" # the base hostname & protocol for your site
copyright: "<a href='http://www.mathieufournier.ca'>Programmation Mathieu Fournier</a>"

# Build settings
markdown: kramdown
